//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MendinePayroll.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Designationmaster
    {
        public int designationid { get; set; }
        public string designationname { get; set; }
        public Nullable<int> postid { get; set; }
        public string deleteflag { get; set; }
        public Nullable<System.DateTime> ceratedon { get; set; }
        public string createdby { get; set; }
        public string designationshortform { get; set; }
    }
}
