//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MendinePayroll.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSalaryConfig
    {
        public int Id { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<int> PayGroupId { get; set; }
        public Nullable<bool> IsPTaxActive { get; set; }
        public string ContinuousAttendanceAllowance { get; set; }
        public string ProductionBonus { get; set; }
    }
}
