//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MendinePayroll.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLoan
    {
        public int LoanId { get; set; }
        public int Empid { get; set; }
        public double LoanAmount { get; set; }
        public Nullable<double> MonthlyInstallment { get; set; }
        public Nullable<bool> IsStart { get; set; }
        public Nullable<System.DateTime> LoanDate { get; set; }
    }
}
