//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MendinePayroll.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanTransaction
    {
        public int LoanTransactionId { get; set; }
        public Nullable<int> LoanId { get; set; }
        public Nullable<int> Empid { get; set; }
        public Nullable<decimal> InstallmentAmount { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public Nullable<decimal> ClosingBalance { get; set; }
        public Nullable<System.DateTime> DateOfInStallment { get; set; }
    }
}
