//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MendinePayroll.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManualSalaryConfig
    {
        public int ID { get; set; }
        public Nullable<int> PayGroupID { get; set; }
        public Nullable<int> ManualPayConfigId { get; set; }
        public Nullable<bool> ISActive { get; set; }
    }
}
