//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MendinePayroll.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class esspEntities : DbContext
    {
        public esspEntities()
            : base("name=esspEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Designation> Designations { get; set; }
        public virtual DbSet<Empbasic> Empbasics { get; set; }
        public virtual DbSet<ConfigureSalaryComponent> ConfigureSalaryComponents { get; set; }
        public virtual DbSet<EmployeeLoan> EmployeeLoans { get; set; }
        public virtual DbSet<LoanTransaction> LoanTransactions { get; set; }
        public virtual DbSet<PayConfig> PayConfigs { get; set; }
        public virtual DbSet<PayGroup> PayGroups { get; set; }
        public virtual DbSet<PayGroupEmployeeMapping> PayGroupEmployeeMappings { get; set; }
        public virtual DbSet<Postmaster> Postmasters { get; set; }
        public virtual DbSet<SalaryComponent> SalaryComponents { get; set; }
        public virtual DbSet<SalaryComponentType> SalaryComponentTypes { get; set; }
        public virtual DbSet<SalaryConfigure> SalaryConfigures { get; set; }
        public virtual DbSet<tcomactiveworklist> tcomactiveworklists { get; set; }
        public virtual DbSet<tcomworklisthistory> tcomworklisthistories { get; set; }
        public virtual DbSet<tleaveappdtl> tleaveappdtls { get; set; }
        public virtual DbSet<tleaveapplicationhrd> tleaveapplicationhrds { get; set; }
        public virtual DbSet<PayGroupBonu> PayGroupBonus { get; set; }
        public virtual DbSet<EmployeeSalary> EmployeeSalaries { get; set; }
        public virtual DbSet<Designationmaster> Designationmasters { get; set; }
        public virtual DbSet<ManualSalaryConfig> ManualSalaryConfigs { get; set; }
        public virtual DbSet<EmpoloyeeSalaryConfigManualValue> EmpoloyeeSalaryConfigManualValues { get; set; }
        public virtual DbSet<EmployeeSalaryConfig> EmployeeSalaryConfigs { get; set; }
    
        public virtual ObjectResult<CalculateTotalLeave_Result> CalculateTotalLeave(Nullable<int> employeeID, Nullable<System.DateTime> fromdate, Nullable<System.DateTime> todate, Nullable<int> mONTH, Nullable<int> yEAR)
        {
            var employeeIDParameter = employeeID.HasValue ?
                new ObjectParameter("EmployeeID", employeeID) :
                new ObjectParameter("EmployeeID", typeof(int));
    
            var fromdateParameter = fromdate.HasValue ?
                new ObjectParameter("fromdate", fromdate) :
                new ObjectParameter("fromdate", typeof(System.DateTime));
    
            var todateParameter = todate.HasValue ?
                new ObjectParameter("todate", todate) :
                new ObjectParameter("todate", typeof(System.DateTime));
    
            var mONTHParameter = mONTH.HasValue ?
                new ObjectParameter("MONTH", mONTH) :
                new ObjectParameter("MONTH", typeof(int));
    
            var yEARParameter = yEAR.HasValue ?
                new ObjectParameter("YEAR", yEAR) :
                new ObjectParameter("YEAR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CalculateTotalLeave_Result>("CalculateTotalLeave", employeeIDParameter, fromdateParameter, todateParameter, mONTHParameter, yEARParameter);
        }
    
        public virtual ObjectResult<ConfigureSalaryComponent_GetAll_Result> ConfigureSalaryComponent_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConfigureSalaryComponent_GetAll_Result>("ConfigureSalaryComponent_GetAll");
        }
    
        public virtual ObjectResult<ConfigureSalaryComponent_GetBYId_Result> ConfigureSalaryComponent_GetBYId(Nullable<int> configureSalaryID)
        {
            var configureSalaryIDParameter = configureSalaryID.HasValue ?
                new ObjectParameter("ConfigureSalaryID", configureSalaryID) :
                new ObjectParameter("ConfigureSalaryID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConfigureSalaryComponent_GetBYId_Result>("ConfigureSalaryComponent_GetBYId", configureSalaryIDParameter);
        }
    
        public virtual int ConfigureSalaryComponent_Save(Nullable<int> configureSalaryID, Nullable<int> payConfigId, string calculationFormula, Nullable<double> manualRate, Nullable<int> masterPayConfigID, Nullable<bool> iSPercentage)
        {
            var configureSalaryIDParameter = configureSalaryID.HasValue ?
                new ObjectParameter("ConfigureSalaryID", configureSalaryID) :
                new ObjectParameter("ConfigureSalaryID", typeof(int));
    
            var payConfigIdParameter = payConfigId.HasValue ?
                new ObjectParameter("PayConfigId", payConfigId) :
                new ObjectParameter("PayConfigId", typeof(int));
    
            var calculationFormulaParameter = calculationFormula != null ?
                new ObjectParameter("CalculationFormula", calculationFormula) :
                new ObjectParameter("CalculationFormula", typeof(string));
    
            var manualRateParameter = manualRate.HasValue ?
                new ObjectParameter("ManualRate", manualRate) :
                new ObjectParameter("ManualRate", typeof(double));
    
            var masterPayConfigIDParameter = masterPayConfigID.HasValue ?
                new ObjectParameter("MasterPayConfigID", masterPayConfigID) :
                new ObjectParameter("MasterPayConfigID", typeof(int));
    
            var iSPercentageParameter = iSPercentage.HasValue ?
                new ObjectParameter("ISPercentage", iSPercentage) :
                new ObjectParameter("ISPercentage", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ConfigureSalaryComponent_Save", configureSalaryIDParameter, payConfigIdParameter, calculationFormulaParameter, manualRateParameter, masterPayConfigIDParameter, iSPercentageParameter);
        }
    
        public virtual ObjectResult<Employee_GetByDesignationID_Result> Employee_GetByDesignationID(string tenantID)
        {
            var tenantIDParameter = tenantID != null ?
                new ObjectParameter("TenantID", tenantID) :
                new ObjectParameter("TenantID", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Employee_GetByDesignationID_Result>("Employee_GetByDesignationID", tenantIDParameter);
        }
    
        public virtual ObjectResult<EmployeeLoan_GetByID_Result> EmployeeLoan_GetByID(Nullable<int> empid)
        {
            var empidParameter = empid.HasValue ?
                new ObjectParameter("Empid", empid) :
                new ObjectParameter("Empid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EmployeeLoan_GetByID_Result>("EmployeeLoan_GetByID", empidParameter);
        }
    
        public virtual int EmployeeLoan_save(Nullable<int> id, Nullable<int> empid, Nullable<double> loanAmount, Nullable<double> monthlyInstallment, Nullable<bool> isStart)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var empidParameter = empid.HasValue ?
                new ObjectParameter("Empid", empid) :
                new ObjectParameter("Empid", typeof(int));
    
            var loanAmountParameter = loanAmount.HasValue ?
                new ObjectParameter("LoanAmount", loanAmount) :
                new ObjectParameter("LoanAmount", typeof(double));
    
            var monthlyInstallmentParameter = monthlyInstallment.HasValue ?
                new ObjectParameter("MonthlyInstallment", monthlyInstallment) :
                new ObjectParameter("MonthlyInstallment", typeof(double));
    
            var isStartParameter = isStart.HasValue ?
                new ObjectParameter("IsStart", isStart) :
                new ObjectParameter("IsStart", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EmployeeLoan_save", idParameter, empidParameter, loanAmountParameter, monthlyInstallmentParameter, isStartParameter);
        }
    
        public virtual ObjectResult<LoanTransaction_GetByID_Result> LoanTransaction_GetByID(Nullable<int> empid)
        {
            var empidParameter = empid.HasValue ?
                new ObjectParameter("Empid", empid) :
                new ObjectParameter("Empid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LoanTransaction_GetByID_Result>("LoanTransaction_GetByID", empidParameter);
        }
    
        public virtual int LoanTransaction_save(Nullable<int> loanId, Nullable<int> empid, Nullable<decimal> installmentAmount, Nullable<decimal> openingBalance, Nullable<decimal> closingBalance)
        {
            var loanIdParameter = loanId.HasValue ?
                new ObjectParameter("LoanId", loanId) :
                new ObjectParameter("LoanId", typeof(int));
    
            var empidParameter = empid.HasValue ?
                new ObjectParameter("Empid", empid) :
                new ObjectParameter("Empid", typeof(int));
    
            var installmentAmountParameter = installmentAmount.HasValue ?
                new ObjectParameter("InstallmentAmount", installmentAmount) :
                new ObjectParameter("InstallmentAmount", typeof(decimal));
    
            var openingBalanceParameter = openingBalance.HasValue ?
                new ObjectParameter("OpeningBalance", openingBalance) :
                new ObjectParameter("OpeningBalance", typeof(decimal));
    
            var closingBalanceParameter = closingBalance.HasValue ?
                new ObjectParameter("ClosingBalance", closingBalance) :
                new ObjectParameter("ClosingBalance", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LoanTransaction_save", loanIdParameter, empidParameter, installmentAmountParameter, openingBalanceParameter, closingBalanceParameter);
        }
    
        public virtual ObjectResult<PayConfig_GetAll_Result> PayConfig_GetAll(string tenantID)
        {
            var tenantIDParameter = tenantID != null ?
                new ObjectParameter("TenantID", tenantID) :
                new ObjectParameter("TenantID", typeof(string));
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PayConfig_GetAll_Result>("PayConfig_GetAll", tenantIDParameter);
        }
    
        public virtual ObjectResult<PayConfig_GetById_Result> PayConfig_GetById(Nullable<int> payConfigId)
        {
            var payConfigIdParameter = payConfigId.HasValue ?
                new ObjectParameter("PayConfigId", payConfigId) :
                new ObjectParameter("PayConfigId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PayConfig_GetById_Result>("PayConfig_GetById", payConfigIdParameter);
        }
    
        public virtual ObjectResult<PayConfig_GetByType_Result> PayConfig_GetByType(string payConfigType,string tenantID)
        {
            var payConfigTypeParameter = payConfigType != null ?
                new ObjectParameter("PayConfigType", payConfigType) :
                new ObjectParameter("PayConfigType", typeof(string));

            var tenantIDParameter = tenantID != null ?
                 new ObjectParameter("TenantID", tenantID) :
                 new ObjectParameter("TenantID", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PayConfig_GetByType_Result>("PayConfig_GetByType", payConfigTypeParameter, tenantIDParameter);
        }
    
        public virtual int PayConfig_Save(Nullable<int> payConfigId, string payConfigName, string payConfigType, Nullable<bool> iScalculative, Nullable<bool> iSstatutory,string tenantId,string entryUser)
        {
            var payConfigIdParameter = payConfigId.HasValue ?
                new ObjectParameter("PayConfigId", payConfigId) :
                new ObjectParameter("PayConfigId", typeof(int));
    
            var payConfigNameParameter = payConfigName != null ?
                new ObjectParameter("PayConfigName", payConfigName) :
                new ObjectParameter("PayConfigName", typeof(string));
    
            var payConfigTypeParameter = payConfigType != null ?
                new ObjectParameter("PayConfigType", payConfigType) :
                new ObjectParameter("PayConfigType", typeof(string));
    
            var iScalculativeParameter = iScalculative.HasValue ?
                new ObjectParameter("IScalculative", iScalculative) :
                new ObjectParameter("IScalculative", typeof(bool));

            var iSstatutoryParameter = iSstatutory.HasValue ?
                new ObjectParameter("IsStatutory", iSstatutory) :
                new ObjectParameter("IsStatutory", typeof(bool));

            var tenantIdParameter = tenantId != null ?
                new ObjectParameter("TenantID", tenantId) :
                new ObjectParameter("TenantID", typeof(string));
            var entryUserParameter = entryUser != null ?
                new ObjectParameter("EntryUser", entryUser) :
                new ObjectParameter("EntryUser", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PayConfig_Save", payConfigIdParameter, payConfigNameParameter, payConfigTypeParameter, iScalculativeParameter,iSstatutoryParameter,tenantIdParameter,entryUserParameter);
        }
    
        public virtual int PayGroup_Delete(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PayGroup_Delete", idParameter);
        }
    
        public virtual ObjectResult<PayGroup_GetAll_Result> PayGroup_GetAll(string tenantID)
        {
            var tenantIDParameter = tenantID != null ?
               new ObjectParameter("TenantID", tenantID) :
               new ObjectParameter("TenantID", typeof(string));
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PayGroup_GetAll_Result>("PayGroup_GetAll", tenantIDParameter);
        }
    
        public virtual ObjectResult<PayGroup_Save_Result> PayGroup_Save(Nullable<int> id, string payGroupName, string description, string payGroupMasterCode, Nullable<int> concernHRPersonnel,string tenantID,string entryUser)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var payGroupNameParameter = payGroupName != null ?
                new ObjectParameter("PayGroupName", payGroupName) :
                new ObjectParameter("PayGroupName", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var payGroupMasterCodeParameter = payGroupMasterCode != null ?
                new ObjectParameter("PayGroupMasterCode", payGroupMasterCode) :
                new ObjectParameter("PayGroupMasterCode", typeof(string));
    
            var concernHRPersonnelParameter = concernHRPersonnel.HasValue ?
                new ObjectParameter("ConcernHRPersonnel", concernHRPersonnel) :
                new ObjectParameter("ConcernHRPersonnel", typeof(int));
            var tenantIDParameter = tenantID != null ?
                new ObjectParameter("TenantID", tenantID) :
                new ObjectParameter("TenantID", typeof(string));
            var entryUserParameter = entryUser != null ?
                new ObjectParameter("EntryUser", entryUser) :
                new ObjectParameter("EntryUser", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PayGroup_Save_Result>("PayGroup_Save", idParameter, payGroupNameParameter, descriptionParameter, payGroupMasterCodeParameter, concernHRPersonnelParameter,tenantIDParameter,entryUserParameter);
        }
    
        public virtual int PayGroupEmployeeMapping_Delete(Nullable<int> payGroupID, Nullable<int> employeeID)
        {
            var payGroupIDParameter = payGroupID.HasValue ?
                new ObjectParameter("PayGroupID", payGroupID) :
                new ObjectParameter("PayGroupID", typeof(int));
    
            var employeeIDParameter = employeeID.HasValue ?
                new ObjectParameter("EmployeeID", employeeID) :
                new ObjectParameter("EmployeeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PayGroupEmployeeMapping_Delete", payGroupIDParameter, employeeIDParameter);
        }
    
        public virtual ObjectResult<PayGroupEmployeeMapping_GetAll_Result> PayGroupEmployeeMapping_GetAll(Nullable<int> payGroupID)
        {
            var payGroupIDParameter = payGroupID.HasValue ?
                new ObjectParameter("PayGroupID", payGroupID) :
                new ObjectParameter("PayGroupID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PayGroupEmployeeMapping_GetAll_Result>("PayGroupEmployeeMapping_GetAll", payGroupIDParameter);
        }
    
        public virtual ObjectResult<PayGroupEmployeeMapping_Save_Result> PayGroupEmployeeMapping_Save(Nullable<int> payGroupID, Nullable<int> employeeID)
        {
            var payGroupIDParameter = payGroupID.HasValue ?
                new ObjectParameter("PayGroupID", payGroupID) :
                new ObjectParameter("PayGroupID", typeof(int));
    
            var employeeIDParameter = employeeID.HasValue ?
                new ObjectParameter("EmployeeID", employeeID) :
                new ObjectParameter("EmployeeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PayGroupEmployeeMapping_Save_Result>("PayGroupEmployeeMapping_Save", payGroupIDParameter, employeeIDParameter);
        }
    
        public virtual int SalaryComponent_Delete(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SalaryComponent_Delete", idParameter);
        }
    
        public virtual ObjectResult<SalaryComponent_GetAll_Result> SalaryComponent_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SalaryComponent_GetAll_Result>("SalaryComponent_GetAll");
        }
    
        public virtual ObjectResult<SalaryComponent_GetById_Result> SalaryComponent_GetById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SalaryComponent_GetById_Result>("SalaryComponent_GetById", idParameter);
        }
    
        public virtual int SalaryComponent_Save(Nullable<int> id, string salaryComponent, Nullable<int> salaryComponentCode, Nullable<int> salaryComponentTypeID, Nullable<int> payGroupID, string description)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var salaryComponentParameter = salaryComponent != null ?
                new ObjectParameter("SalaryComponent", salaryComponent) :
                new ObjectParameter("SalaryComponent", typeof(string));
    
            var salaryComponentCodeParameter = salaryComponentCode.HasValue ?
                new ObjectParameter("SalaryComponentCode", salaryComponentCode) :
                new ObjectParameter("SalaryComponentCode", typeof(int));
    
            var salaryComponentTypeIDParameter = salaryComponentTypeID.HasValue ?
                new ObjectParameter("SalaryComponentTypeID", salaryComponentTypeID) :
                new ObjectParameter("SalaryComponentTypeID", typeof(int));
    
            var payGroupIDParameter = payGroupID.HasValue ?
                new ObjectParameter("PayGroupID", payGroupID) :
                new ObjectParameter("PayGroupID", typeof(int));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SalaryComponent_Save", idParameter, salaryComponentParameter, salaryComponentCodeParameter, salaryComponentTypeIDParameter, payGroupIDParameter, descriptionParameter);
        }
    
        public virtual int SalaryComponentType_Delete(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SalaryComponentType_Delete", idParameter);
        }
    
        public virtual ObjectResult<SalaryComponentType_GetAll_Result> SalaryComponentType_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SalaryComponentType_GetAll_Result>("SalaryComponentType_GetAll");
        }
    
        public virtual ObjectResult<SalaryComponentType_GetById_Result> SalaryComponentType_GetById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SalaryComponentType_GetById_Result>("SalaryComponentType_GetById", idParameter);
        }
    
        public virtual int SalaryComponentType_Save(Nullable<int> id, string salaryComponentType)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var salaryComponentTypeParameter = salaryComponentType != null ?
                new ObjectParameter("SalaryComponentType", salaryComponentType) :
                new ObjectParameter("SalaryComponentType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SalaryComponentType_Save", idParameter, salaryComponentTypeParameter);
        }
    
        public virtual ObjectResult<SalaryConfigure_GetAll_Result> SalaryConfigure_GetAll(string tenantID)
        {
            var tenantIDParameter = tenantID != null ?
                new ObjectParameter("TenantID", tenantID) :
                new ObjectParameter("TenantID", typeof(string));
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SalaryConfigure_GetAll_Result>("SalaryConfigure_GetAll", tenantIDParameter);
        }
    
        public virtual ObjectResult<SalaryConfigure_GetById_Result> SalaryConfigure_GetById(Nullable<int> salaryConfigureID)
        {
            var salaryConfigureIDParameter = salaryConfigureID.HasValue ?
                new ObjectParameter("SalaryConfigureID", salaryConfigureID) :
                new ObjectParameter("SalaryConfigureID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SalaryConfigure_GetById_Result>("SalaryConfigure_GetById", salaryConfigureIDParameter);
        }
    
        public virtual ObjectResult<SalaryConfigure_Save_Result> SalaryConfigure_Save(Nullable<int> salaryConfigureID, string salaryConfigureName, Nullable<int> payGroupID, Nullable<int> salaryConfigureType)
        {
            var salaryConfigureIDParameter = salaryConfigureID.HasValue ?
                new ObjectParameter("SalaryConfigureID", salaryConfigureID) :
                new ObjectParameter("SalaryConfigureID", typeof(int));
    
            var salaryConfigureNameParameter = salaryConfigureName != null ?
                new ObjectParameter("SalaryConfigureName", salaryConfigureName) :
                new ObjectParameter("SalaryConfigureName", typeof(string));
    
            var payGroupIDParameter = payGroupID.HasValue ?
                new ObjectParameter("PayGroupID", payGroupID) :
                new ObjectParameter("PayGroupID", typeof(int));
    
            var salaryConfigureTypeParameter = salaryConfigureType.HasValue ?
                new ObjectParameter("SalaryConfigureType", salaryConfigureType) :
                new ObjectParameter("SalaryConfigureType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SalaryConfigure_Save_Result>("SalaryConfigure_Save", salaryConfigureIDParameter, salaryConfigureNameParameter, payGroupIDParameter, salaryConfigureTypeParameter);
        }
    
        public virtual int Sp_CreatePayGroup(string payGroupName, string description, string payGroupMasterCode, Nullable<int> concernHRPersonnel)
        {
            var payGroupNameParameter = payGroupName != null ?
                new ObjectParameter("PayGroupName", payGroupName) :
                new ObjectParameter("PayGroupName", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var payGroupMasterCodeParameter = payGroupMasterCode != null ?
                new ObjectParameter("PayGroupMasterCode", payGroupMasterCode) :
                new ObjectParameter("PayGroupMasterCode", typeof(string));
    
            var concernHRPersonnelParameter = concernHRPersonnel.HasValue ?
                new ObjectParameter("ConcernHRPersonnel", concernHRPersonnel) :
                new ObjectParameter("ConcernHRPersonnel", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_CreatePayGroup", payGroupNameParameter, descriptionParameter, payGroupMasterCodeParameter, concernHRPersonnelParameter);
        }
    
        public virtual int Sp_DeletePayGroup(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_DeletePayGroup", idParameter);
        }
    
        public virtual ObjectResult<Sp_GetPayGroupById_Result> Sp_GetPayGroupById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetPayGroupById_Result>("Sp_GetPayGroupById", idParameter);
        }
    
        public virtual ObjectResult<Sp_ListPayGroup_Result> Sp_ListPayGroup()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_ListPayGroup_Result>("Sp_ListPayGroup");
        }
    
        public virtual int Sp_UpdatePayGroup(Nullable<int> id, string payGroupName, string description, string payGroupMasterCode, Nullable<int> concernHRPersonnel)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var payGroupNameParameter = payGroupName != null ?
                new ObjectParameter("PayGroupName", payGroupName) :
                new ObjectParameter("PayGroupName", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var payGroupMasterCodeParameter = payGroupMasterCode != null ?
                new ObjectParameter("PayGroupMasterCode", payGroupMasterCode) :
                new ObjectParameter("PayGroupMasterCode", typeof(string));
    
            var concernHRPersonnelParameter = concernHRPersonnel.HasValue ?
                new ObjectParameter("ConcernHRPersonnel", concernHRPersonnel) :
                new ObjectParameter("ConcernHRPersonnel", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_UpdatePayGroup", idParameter, payGroupNameParameter, descriptionParameter, payGroupMasterCodeParameter, concernHRPersonnelParameter);
        }
    
        public virtual ObjectResult<PayGroupBonus_GetAllByID_Result> PayGroupBonus_GetAllByID(Nullable<int> paygroupID)
        {
            var paygroupIDParameter = paygroupID.HasValue ?
                new ObjectParameter("PaygroupID", paygroupID) :
                new ObjectParameter("PaygroupID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PayGroupBonus_GetAllByID_Result>("PayGroupBonus_GetAllByID", paygroupIDParameter);
        }
    
        public virtual ObjectResult<PayGroupBonus_GetById_Result> PayGroupBonus_GetById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PayGroupBonus_GetById_Result>("PayGroupBonus_GetById", idParameter);
        }
    
        public virtual ObjectResult<PayGroupBonus_GetByMonthandPaygroupId_Result> PayGroupBonus_GetByMonthandPaygroupId(Nullable<int> payGroupId, string month, Nullable<int> year)
        {
            var payGroupIdParameter = payGroupId.HasValue ?
                new ObjectParameter("PayGroupId", payGroupId) :
                new ObjectParameter("PayGroupId", typeof(int));
    
            var monthParameter = month != null ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(string));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PayGroupBonus_GetByMonthandPaygroupId_Result>("PayGroupBonus_GetByMonthandPaygroupId", payGroupIdParameter, monthParameter, yearParameter);
        }
    
        public virtual ObjectResult<EmployeeSalary_duplicateCheck_Result> EmployeeSalary_duplicateCheck(Nullable<int> empid, string month, Nullable<int> year)
        {
            var empidParameter = empid.HasValue ?
                new ObjectParameter("Empid", empid) :
                new ObjectParameter("Empid", typeof(int));
    
            var monthParameter = month != null ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(string));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EmployeeSalary_duplicateCheck_Result>("EmployeeSalary_duplicateCheck", empidParameter, monthParameter, yearParameter);
        }
    
        public virtual int ConfigureSalaryComponent_Update(Nullable<int> configureSalaryID, Nullable<int> payConfigId, string calculationFormula, Nullable<double> manualRate, Nullable<int> masterPayConfigID, Nullable<bool> iSPercentage)
        {
            var configureSalaryIDParameter = configureSalaryID.HasValue ?
                new ObjectParameter("ConfigureSalaryID", configureSalaryID) :
                new ObjectParameter("ConfigureSalaryID", typeof(int));
    
            var payConfigIdParameter = payConfigId.HasValue ?
                new ObjectParameter("PayConfigId", payConfigId) :
                new ObjectParameter("PayConfigId", typeof(int));
    
            var calculationFormulaParameter = calculationFormula != null ?
                new ObjectParameter("CalculationFormula", calculationFormula) :
                new ObjectParameter("CalculationFormula", typeof(string));
    
            var manualRateParameter = manualRate.HasValue ?
                new ObjectParameter("ManualRate", manualRate) :
                new ObjectParameter("ManualRate", typeof(double));
    
            var masterPayConfigIDParameter = masterPayConfigID.HasValue ?
                new ObjectParameter("MasterPayConfigID", masterPayConfigID) :
                new ObjectParameter("MasterPayConfigID", typeof(int));
    
            var iSPercentageParameter = iSPercentage.HasValue ?
                new ObjectParameter("ISPercentage", iSPercentage) :
                new ObjectParameter("ISPercentage", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ConfigureSalaryComponent_Update", configureSalaryIDParameter, payConfigIdParameter, calculationFormulaParameter, manualRateParameter, masterPayConfigIDParameter, iSPercentageParameter);
        }
    
        public virtual ObjectResult<PayGroupBonus_Save_Result> PayGroupBonus_Save(Nullable<int> id, Nullable<int> payGroupID, string month, Nullable<int> year, Nullable<double> overTimeHours, Nullable<double> productionBonus, Nullable<double> targetAchieved)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var payGroupIDParameter = payGroupID.HasValue ?
                new ObjectParameter("PayGroupID", payGroupID) :
                new ObjectParameter("PayGroupID", typeof(int));
    
            var monthParameter = month != null ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(string));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            var overTimeHoursParameter = overTimeHours.HasValue ?
                new ObjectParameter("OverTimeHours", overTimeHours) :
                new ObjectParameter("OverTimeHours", typeof(double));
    
            var productionBonusParameter = productionBonus.HasValue ?
                new ObjectParameter("ProductionBonus", productionBonus) :
                new ObjectParameter("ProductionBonus", typeof(double));
    
            var targetAchievedParameter = targetAchieved.HasValue ?
                new ObjectParameter("TargetAchieved", targetAchieved) :
                new ObjectParameter("TargetAchieved", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PayGroupBonus_Save_Result>("PayGroupBonus_Save", idParameter, payGroupIDParameter, monthParameter, yearParameter, overTimeHoursParameter, productionBonusParameter, targetAchievedParameter);
        }
    
        public virtual ObjectResult<EmployeeSalary_TotalnoByMonth_Result> EmployeeSalary_TotalnoByMonth(string month, Nullable<int> year)
        {
            var monthParameter = month != null ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(string));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EmployeeSalary_TotalnoByMonth_Result>("EmployeeSalary_TotalnoByMonth", monthParameter, yearParameter);
        }
    
        public virtual ObjectResult<ExcelReport_GetaAll_Result> ExcelReport_GetaAll(Nullable<int> empid, string fromdate, string todate, string month, Nullable<int> totalDays, Nullable<int> empno, Nullable<int> year)
        {
            var empidParameter = empid.HasValue ?
                new ObjectParameter("Empid", empid) :
                new ObjectParameter("Empid", typeof(int));
    
            var fromdateParameter = fromdate != null ?
                new ObjectParameter("fromdate", fromdate) :
                new ObjectParameter("fromdate", typeof(string));
    
            var todateParameter = todate != null ?
                new ObjectParameter("todate", todate) :
                new ObjectParameter("todate", typeof(string));
    
            var monthParameter = month != null ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(string));
    
            var totalDaysParameter = totalDays.HasValue ?
                new ObjectParameter("TotalDays", totalDays) :
                new ObjectParameter("TotalDays", typeof(int));
    
            var empnoParameter = empno.HasValue ?
                new ObjectParameter("empno", empno) :
                new ObjectParameter("empno", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ExcelReport_GetaAll_Result>("ExcelReport_GetaAll", empidParameter, fromdateParameter, todateParameter, monthParameter, totalDaysParameter, empnoParameter, yearParameter);
        }
    
        public virtual int EmployeeSalary_save(Nullable<int> empid, Nullable<int> empno, Nullable<int> paygroupId, Nullable<double> basic, Nullable<double> hRA, Nullable<double> attireAllowance, Nullable<double> internetAllowance, Nullable<double> mobileAllowance, Nullable<double> pF, Nullable<double> eSI, Nullable<double> pTax, Nullable<double> educationAllowances, Nullable<double> medicalAllowances, Nullable<double> lTA, Nullable<double> grossAmount, Nullable<double> loanInstallment, Nullable<double> continuousAttendanceAllowance, Nullable<double> overtimeAllowance, Nullable<double> lodgingAllowance, Nullable<double> productionBonus, Nullable<double> leaveamount, Nullable<double> totalAllowances, Nullable<double> totalDeduction, Nullable<double> netPayableAmount, string month, Nullable<int> year, Nullable<double> stipend, Nullable<double> arrears, Nullable<double> performanceallowance, Nullable<double> specialallowance, Nullable<double> booksPeriodical, Nullable<double> conveyenceAllowance, Nullable<double> trainingAllowance, Nullable<double> vehicalAllowance, Nullable<double> foodAllowance, Nullable<double> tDS)
        {
            var empidParameter = empid.HasValue ?
                new ObjectParameter("Empid", empid) :
                new ObjectParameter("Empid", typeof(int));
    
            var empnoParameter = empno.HasValue ?
                new ObjectParameter("Empno", empno) :
                new ObjectParameter("Empno", typeof(int));
    
            var paygroupIdParameter = paygroupId.HasValue ?
                new ObjectParameter("PaygroupId", paygroupId) :
                new ObjectParameter("PaygroupId", typeof(int));
    
            var basicParameter = basic.HasValue ?
                new ObjectParameter("Basic", basic) :
                new ObjectParameter("Basic", typeof(double));
    
            var hRAParameter = hRA.HasValue ?
                new ObjectParameter("HRA", hRA) :
                new ObjectParameter("HRA", typeof(double));
    
            var attireAllowanceParameter = attireAllowance.HasValue ?
                new ObjectParameter("AttireAllowance", attireAllowance) :
                new ObjectParameter("AttireAllowance", typeof(double));
    
            var internetAllowanceParameter = internetAllowance.HasValue ?
                new ObjectParameter("InternetAllowance", internetAllowance) :
                new ObjectParameter("InternetAllowance", typeof(double));
    
            var mobileAllowanceParameter = mobileAllowance.HasValue ?
                new ObjectParameter("MobileAllowance", mobileAllowance) :
                new ObjectParameter("MobileAllowance", typeof(double));
    
            var pFParameter = pF.HasValue ?
                new ObjectParameter("PF", pF) :
                new ObjectParameter("PF", typeof(double));
    
            var eSIParameter = eSI.HasValue ?
                new ObjectParameter("ESI", eSI) :
                new ObjectParameter("ESI", typeof(double));
    
            var pTaxParameter = pTax.HasValue ?
                new ObjectParameter("PTax", pTax) :
                new ObjectParameter("PTax", typeof(double));
    
            var educationAllowancesParameter = educationAllowances.HasValue ?
                new ObjectParameter("EducationAllowances", educationAllowances) :
                new ObjectParameter("EducationAllowances", typeof(double));
    
            var medicalAllowancesParameter = medicalAllowances.HasValue ?
                new ObjectParameter("MedicalAllowances", medicalAllowances) :
                new ObjectParameter("MedicalAllowances", typeof(double));
    
            var lTAParameter = lTA.HasValue ?
                new ObjectParameter("LTA", lTA) :
                new ObjectParameter("LTA", typeof(double));
    
            var grossAmountParameter = grossAmount.HasValue ?
                new ObjectParameter("GrossAmount", grossAmount) :
                new ObjectParameter("GrossAmount", typeof(double));
    
            var loanInstallmentParameter = loanInstallment.HasValue ?
                new ObjectParameter("LoanInstallment", loanInstallment) :
                new ObjectParameter("LoanInstallment", typeof(double));
    
            var continuousAttendanceAllowanceParameter = continuousAttendanceAllowance.HasValue ?
                new ObjectParameter("ContinuousAttendanceAllowance", continuousAttendanceAllowance) :
                new ObjectParameter("ContinuousAttendanceAllowance", typeof(double));
    
            var overtimeAllowanceParameter = overtimeAllowance.HasValue ?
                new ObjectParameter("OvertimeAllowance", overtimeAllowance) :
                new ObjectParameter("OvertimeAllowance", typeof(double));
    
            var lodgingAllowanceParameter = lodgingAllowance.HasValue ?
                new ObjectParameter("LodgingAllowance", lodgingAllowance) :
                new ObjectParameter("LodgingAllowance", typeof(double));
    
            var productionBonusParameter = productionBonus.HasValue ?
                new ObjectParameter("ProductionBonus", productionBonus) :
                new ObjectParameter("ProductionBonus", typeof(double));
    
            var leaveamountParameter = leaveamount.HasValue ?
                new ObjectParameter("Leaveamount", leaveamount) :
                new ObjectParameter("Leaveamount", typeof(double));
    
            var totalAllowancesParameter = totalAllowances.HasValue ?
                new ObjectParameter("TotalAllowances", totalAllowances) :
                new ObjectParameter("TotalAllowances", typeof(double));
    
            var totalDeductionParameter = totalDeduction.HasValue ?
                new ObjectParameter("TotalDeduction", totalDeduction) :
                new ObjectParameter("TotalDeduction", typeof(double));
    
            var netPayableAmountParameter = netPayableAmount.HasValue ?
                new ObjectParameter("NetPayableAmount", netPayableAmount) :
                new ObjectParameter("NetPayableAmount", typeof(double));
    
            var monthParameter = month != null ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(string));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var stipendParameter = stipend.HasValue ?
                new ObjectParameter("Stipend", stipend) :
                new ObjectParameter("Stipend", typeof(double));
    
            var arrearsParameter = arrears.HasValue ?
                new ObjectParameter("Arrears", arrears) :
                new ObjectParameter("Arrears", typeof(double));
    
            var performanceallowanceParameter = performanceallowance.HasValue ?
                new ObjectParameter("performanceallowance", performanceallowance) :
                new ObjectParameter("performanceallowance", typeof(double));
    
            var specialallowanceParameter = specialallowance.HasValue ?
                new ObjectParameter("Specialallowance", specialallowance) :
                new ObjectParameter("Specialallowance", typeof(double));
    
            var booksPeriodicalParameter = booksPeriodical.HasValue ?
                new ObjectParameter("BooksPeriodical", booksPeriodical) :
                new ObjectParameter("BooksPeriodical", typeof(double));
    
            var conveyenceAllowanceParameter = conveyenceAllowance.HasValue ?
                new ObjectParameter("ConveyenceAllowance", conveyenceAllowance) :
                new ObjectParameter("ConveyenceAllowance", typeof(double));
    
            var trainingAllowanceParameter = trainingAllowance.HasValue ?
                new ObjectParameter("TrainingAllowance", trainingAllowance) :
                new ObjectParameter("TrainingAllowance", typeof(double));
    
            var vehicalAllowanceParameter = vehicalAllowance.HasValue ?
                new ObjectParameter("VehicalAllowance", vehicalAllowance) :
                new ObjectParameter("VehicalAllowance", typeof(double));
    
            var foodAllowanceParameter = foodAllowance.HasValue ?
                new ObjectParameter("FoodAllowance", foodAllowance) :
                new ObjectParameter("FoodAllowance", typeof(double));
    
            var tDSParameter = tDS.HasValue ?
                new ObjectParameter("TDS", tDS) :
                new ObjectParameter("TDS", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EmployeeSalary_save", empidParameter, empnoParameter, paygroupIdParameter, basicParameter, hRAParameter, attireAllowanceParameter, internetAllowanceParameter, mobileAllowanceParameter, pFParameter, eSIParameter, pTaxParameter, educationAllowancesParameter, medicalAllowancesParameter, lTAParameter, grossAmountParameter, loanInstallmentParameter, continuousAttendanceAllowanceParameter, overtimeAllowanceParameter, lodgingAllowanceParameter, productionBonusParameter, leaveamountParameter, totalAllowancesParameter, totalDeductionParameter, netPayableAmountParameter, monthParameter, yearParameter, stipendParameter, arrearsParameter, performanceallowanceParameter, specialallowanceParameter, booksPeriodicalParameter, conveyenceAllowanceParameter, trainingAllowanceParameter, vehicalAllowanceParameter, foodAllowanceParameter, tDSParameter);
        }
    
        public virtual ObjectResult<PayGroup_GetById_Result> PayGroup_GetById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PayGroup_GetById_Result>("PayGroup_GetById", idParameter);
        }
    
        public virtual ObjectResult<EmployeeLoginCheck_Result> EmployeeLoginCheck(string empemail, string empcode)
        {
            var empemailParameter = empemail != null ?
                new ObjectParameter("empemail", empemail) :
                new ObjectParameter("empemail", typeof(string));
    
            var empcodeParameter = empcode != null ?
                new ObjectParameter("empcode", empcode) :
                new ObjectParameter("empcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EmployeeLoginCheck_Result>("EmployeeLoginCheck", empemailParameter, empcodeParameter);
        }
    
        public virtual ObjectResult<ManualSalaryConfig_GetByPayGroupID_Result> ManualSalaryConfig_GetByPayGroupID(Nullable<int> payGroupID)
        {
            var payGroupIDParameter = payGroupID.HasValue ?
                new ObjectParameter("PayGroupID", payGroupID) :
                new ObjectParameter("PayGroupID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ManualSalaryConfig_GetByPayGroupID_Result>("ManualSalaryConfig_GetByPayGroupID", payGroupIDParameter);
        }
    
        public virtual int ManualSalaryConfig_save(Nullable<int> payGroupID, Nullable<int> manualPayConfigId, Nullable<bool> iSActive)
        {
            var payGroupIDParameter = payGroupID.HasValue ?
                new ObjectParameter("PayGroupID", payGroupID) :
                new ObjectParameter("PayGroupID", typeof(int));
    
            var manualPayConfigIdParameter = manualPayConfigId.HasValue ?
                new ObjectParameter("ManualPayConfigId", manualPayConfigId) :
                new ObjectParameter("ManualPayConfigId", typeof(int));
    
            var iSActiveParameter = iSActive.HasValue ?
                new ObjectParameter("ISActive", iSActive) :
                new ObjectParameter("ISActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ManualSalaryConfig_save", payGroupIDParameter, manualPayConfigIdParameter, iSActiveParameter);
        }
    
        public virtual ObjectResult<SalaryConfigure_PaygroupDuplicatecheck_Result> SalaryConfigure_PaygroupDuplicatecheck(Nullable<int> payGroupID)
        {
            var payGroupIDParameter = payGroupID.HasValue ?
                new ObjectParameter("PayGroupID", payGroupID) :
                new ObjectParameter("PayGroupID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SalaryConfigure_PaygroupDuplicatecheck_Result>("SalaryConfigure_PaygroupDuplicatecheck", payGroupIDParameter);
        }
    
        public virtual int PayConfig_Delete(Nullable<int> payconfigid)
        {
            var payconfigidParameter = payconfigid.HasValue ?
                new ObjectParameter("Payconfigid", payconfigid) :
                new ObjectParameter("Payconfigid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PayConfig_Delete", payconfigidParameter);
        }
    
        public virtual ObjectResult<EmployeeList_Get_Result> EmployeeList_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EmployeeList_Get_Result>("EmployeeList_Get");
        }
    
        public virtual ObjectResult<EmployeeSalaryConfig_Save_Result> EmployeeSalaryConfig_Save(Nullable<int> id, Nullable<int> empId, Nullable<int> payGroupId, Nullable<bool> isPTaxActive, string continuousAllowance, string productionbonus)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var empIdParameter = empId.HasValue ?
                new ObjectParameter("EmpId", empId) :
                new ObjectParameter("EmpId", typeof(int));
    
            var payGroupIdParameter = payGroupId.HasValue ?
                new ObjectParameter("PayGroupId", payGroupId) :
                new ObjectParameter("PayGroupId", typeof(int));
    
            var isPTaxActiveParameter = isPTaxActive.HasValue ?
                new ObjectParameter("IsPTaxActive", isPTaxActive) :
                new ObjectParameter("IsPTaxActive", typeof(bool));
    
            var continuousAllowanceParameter = continuousAllowance != null ?
                new ObjectParameter("ContinuousAllowance", continuousAllowance) :
                new ObjectParameter("ContinuousAllowance", typeof(string));
    
            var productionbonusParameter = productionbonus != null ?
                new ObjectParameter("Productionbonus", productionbonus) :
                new ObjectParameter("Productionbonus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EmployeeSalaryConfig_Save_Result>("EmployeeSalaryConfig_Save", idParameter, empIdParameter, payGroupIdParameter, isPTaxActiveParameter, continuousAllowanceParameter, productionbonusParameter);
        }
    
        public virtual ObjectResult<EmployeeSalaryConfig_GetByID_Result> EmployeeSalaryConfig_GetByID(Nullable<int> empid)
        {
            var empidParameter = empid.HasValue ?
                new ObjectParameter("Empid", empid) :
                new ObjectParameter("Empid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EmployeeSalaryConfig_GetByID_Result>("EmployeeSalaryConfig_GetByID", empidParameter);
        }
    
        public virtual int EmpoloyeeSalaryConfigManualValues_Save(Nullable<int> employeeSalaryConfigid, string payConfigID, string values)
        {
            var employeeSalaryConfigidParameter = employeeSalaryConfigid.HasValue ?
                new ObjectParameter("EmployeeSalaryConfigid", employeeSalaryConfigid) :
                new ObjectParameter("EmployeeSalaryConfigid", typeof(int));
    
            var payConfigIDParameter = payConfigID != null ?
                new ObjectParameter("PayConfigID", payConfigID) :
                new ObjectParameter("PayConfigID", typeof(string));
    
            var valuesParameter = values != null ?
                new ObjectParameter("Values", values) :
                new ObjectParameter("Values", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EmpoloyeeSalaryConfigManualValues_Save", employeeSalaryConfigidParameter, payConfigIDParameter, valuesParameter);
        }
    
        public virtual int EmpoloyeeSalaryConfigManualValues_Update(string payConfigIDs, string payConfigValues, Nullable<int> salaryConfigID)
        {
            var payConfigIDsParameter = payConfigIDs != null ?
                new ObjectParameter("PayConfigIDs", payConfigIDs) :
                new ObjectParameter("PayConfigIDs", typeof(string));
    
            var payConfigValuesParameter = payConfigValues != null ?
                new ObjectParameter("PayConfigValues", payConfigValues) :
                new ObjectParameter("PayConfigValues", typeof(string));
    
            var salaryConfigIDParameter = salaryConfigID.HasValue ?
                new ObjectParameter("SalaryConfigID", salaryConfigID) :
                new ObjectParameter("SalaryConfigID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EmpoloyeeSalaryConfigManualValues_Update", payConfigIDsParameter, payConfigValuesParameter, salaryConfigIDParameter);
        }
    
        [DbFunction("esspEntities", "splitstring")]
        public virtual IQueryable<string> splitstring(string stringToSplit)
        {
            var stringToSplitParameter = stringToSplit != null ?
                new ObjectParameter("stringToSplit", stringToSplit) :
                new ObjectParameter("stringToSplit", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<string>("[esspEntities].[splitstring](@stringToSplit)", stringToSplitParameter);
        }
    
        public virtual ObjectResult<EmployeeList_GetInActive_Result> EmployeeList_GetInActive()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EmployeeList_GetInActive_Result>("EmployeeList_GetInActive");
        }
    
        public virtual ObjectResult<GetEmmployeeDetails_ById_Result> GetEmmployeeDetails_ById(Nullable<int> empid)
        {
            var empidParameter = empid.HasValue ?
                new ObjectParameter("empid", empid) :
                new ObjectParameter("empid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEmmployeeDetails_ById_Result>("GetEmmployeeDetails_ById", empidParameter);
        }
    
        public virtual ObjectResult<EmployeeList_GetbyID_Result> EmployeeList_GetbyID(Nullable<int> empid)
        {
            var empidParameter = empid.HasValue ?
                new ObjectParameter("empid", empid) :
                new ObjectParameter("empid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EmployeeList_GetbyID_Result>("EmployeeList_GetbyID", empidParameter);
        }
    
        public virtual int EmployeeSalary_UpdatePayment(Nullable<int> empid, string month, Nullable<int> year)
        {
            var empidParameter = empid.HasValue ?
                new ObjectParameter("Empid", empid) :
                new ObjectParameter("Empid", typeof(int));
    
            var monthParameter = month != null ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(string));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EmployeeSalary_UpdatePayment", empidParameter, monthParameter, yearParameter);
        }
    
        public virtual ObjectResult<EmployeeBonus_GetAllByEmpid_Result> EmployeeBonus_GetAllByEmpid(Nullable<int> iD, Nullable<int> empid)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var empidParameter = empid.HasValue ?
                new ObjectParameter("Empid", empid) :
                new ObjectParameter("Empid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EmployeeBonus_GetAllByEmpid_Result>("EmployeeBonus_GetAllByEmpid", iDParameter, empidParameter);
        }
    
        public virtual ObjectResult<EmployeeBonus_GetByMonth_Result> EmployeeBonus_GetByMonth(Nullable<int> empid, string month, Nullable<int> year)
        {
            var empidParameter = empid.HasValue ?
                new ObjectParameter("Empid", empid) :
                new ObjectParameter("Empid", typeof(int));
    
            var monthParameter = month != null ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(string));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EmployeeBonus_GetByMonth_Result>("EmployeeBonus_GetByMonth", empidParameter, monthParameter, yearParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> EmployeeBonus_Save(Nullable<int> id, Nullable<int> empid, Nullable<int> payGroupID, string month, Nullable<int> year, Nullable<double> overTimeHours, Nullable<double> productionBonus, Nullable<double> targetAchieved)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var empidParameter = empid.HasValue ?
                new ObjectParameter("Empid", empid) :
                new ObjectParameter("Empid", typeof(int));
    
            var payGroupIDParameter = payGroupID.HasValue ?
                new ObjectParameter("PayGroupID", payGroupID) :
                new ObjectParameter("PayGroupID", typeof(int));
    
            var monthParameter = month != null ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(string));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            var overTimeHoursParameter = overTimeHours.HasValue ?
                new ObjectParameter("OverTimeHours", overTimeHours) :
                new ObjectParameter("OverTimeHours", typeof(double));
    
            var productionBonusParameter = productionBonus.HasValue ?
                new ObjectParameter("ProductionBonus", productionBonus) :
                new ObjectParameter("ProductionBonus", typeof(double));
    
            var targetAchievedParameter = targetAchieved.HasValue ?
                new ObjectParameter("TargetAchieved", targetAchieved) :
                new ObjectParameter("TargetAchieved", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("EmployeeBonus_Save", idParameter, empidParameter, payGroupIDParameter, monthParameter, yearParameter, overTimeHoursParameter, productionBonusParameter, targetAchievedParameter);
        }
    
        public virtual int EmployeeSalary_DeleteAllByMonth(Nullable<int> empid, string month, Nullable<int> year)
        {
            var empidParameter = empid.HasValue ?
                new ObjectParameter("Empid", empid) :
                new ObjectParameter("Empid", typeof(int));
    
            var monthParameter = month != null ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(string));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EmployeeSalary_DeleteAllByMonth", empidParameter, monthParameter, yearParameter);
        }
    
        public virtual ObjectResult<Employee_TDSReport_Result> Employee_TDSReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Employee_TDSReport_Result>("Employee_TDSReport");
        }
    
        public virtual ObjectResult<ExcelReport_GetAll_Result> ExcelReport_GetAll(Nullable<int> empid, Nullable<System.DateTime> fromdate, Nullable<System.DateTime> todate, string month, Nullable<int> totalDays, Nullable<int> empno, Nullable<int> year)
        {
            var empidParameter = empid.HasValue ?
                new ObjectParameter("Empid", empid) :
                new ObjectParameter("Empid", typeof(int));
    
            var fromdateParameter = fromdate.HasValue ?
                new ObjectParameter("fromdate", fromdate) :
                new ObjectParameter("fromdate", typeof(System.DateTime));
    
            var todateParameter = todate.HasValue ?
                new ObjectParameter("todate", todate) :
                new ObjectParameter("todate", typeof(System.DateTime));
    
            var monthParameter = month != null ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(string));
    
            var totalDaysParameter = totalDays.HasValue ?
                new ObjectParameter("TotalDays", totalDays) :
                new ObjectParameter("TotalDays", typeof(int));
    
            var empnoParameter = empno.HasValue ?
                new ObjectParameter("empno", empno) :
                new ObjectParameter("empno", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ExcelReport_GetAll_Result>("ExcelReport_GetAll", empidParameter, fromdateParameter, todateParameter, monthParameter, totalDaysParameter, empnoParameter, yearParameter);
        }
    
        public virtual int SalaryConfigure_Delete(Nullable<int> configureSalaryId)
        {
            var configureSalaryIdParameter = configureSalaryId.HasValue ?
                new ObjectParameter("ConfigureSalaryId", configureSalaryId) :
                new ObjectParameter("ConfigureSalaryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SalaryConfigure_Delete", configureSalaryIdParameter);
        }
    
        public virtual ObjectResult<LeaveDetails_GetByEmpno_Result> LeaveDetails_GetByEmpno(Nullable<int> empno, string month, Nullable<int> year)
        {
            var empnoParameter = empno.HasValue ?
                new ObjectParameter("Empno", empno) :
                new ObjectParameter("Empno", typeof(int));
    
            var monthParameter = month != null ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(string));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LeaveDetails_GetByEmpno_Result>("LeaveDetails_GetByEmpno", empnoParameter, monthParameter, yearParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> LeaveDetails_Save(Nullable<int> empno, Nullable<double> leaveDays, Nullable<double> lateLeaveDays, Nullable<int> createdBy, string month, Nullable<int> year, Nullable<double> noofdaysabsent, string type)
        {
            var empnoParameter = empno.HasValue ?
                new ObjectParameter("Empno", empno) :
                new ObjectParameter("Empno", typeof(int));
    
            var leaveDaysParameter = leaveDays.HasValue ?
                new ObjectParameter("LeaveDays", leaveDays) :
                new ObjectParameter("LeaveDays", typeof(double));
    
            var lateLeaveDaysParameter = lateLeaveDays.HasValue ?
                new ObjectParameter("LateLeaveDays", lateLeaveDays) :
                new ObjectParameter("LateLeaveDays", typeof(double));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            var monthParameter = month != null ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(string));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            var noofdaysabsentParameter = noofdaysabsent.HasValue ?
                new ObjectParameter("Noofdaysabsent", noofdaysabsent) :
                new ObjectParameter("Noofdaysabsent", typeof(double));
    
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("LeaveDetails_Save", empnoParameter, leaveDaysParameter, lateLeaveDaysParameter, createdByParameter, monthParameter, yearParameter, noofdaysabsentParameter, typeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> EmployeeList_Get_Count(string searchval)
        {
            var searchvalParameter = searchval != null ?
                new ObjectParameter("Searchval", searchval) :
                new ObjectParameter("Searchval", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("EmployeeList_Get_Count", searchvalParameter);
        }
    
        public virtual ObjectResult<EmployeeList_Get_List_Result> EmployeeList_Get_List(Nullable<int> pageNumber, Nullable<int> rowsOfPage, string searchval)
        {
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("PageNumber", pageNumber) :
                new ObjectParameter("PageNumber", typeof(int));
    
            var rowsOfPageParameter = rowsOfPage.HasValue ?
                new ObjectParameter("RowsOfPage", rowsOfPage) :
                new ObjectParameter("RowsOfPage", typeof(int));
    
            var searchvalParameter = searchval != null ?
                new ObjectParameter("Searchval", searchval) :
                new ObjectParameter("Searchval", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EmployeeList_Get_List_Result>("EmployeeList_Get_List", pageNumberParameter, rowsOfPageParameter, searchvalParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Employeesalary_viewAllByMonth_Count(string month, Nullable<int> year, Nullable<int> empid, string status)
        {
            var monthParameter = month != null ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(string));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var empidParameter = empid.HasValue ?
                new ObjectParameter("Empid", empid) :
                new ObjectParameter("Empid", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Employeesalary_viewAllByMonth_Count", monthParameter, yearParameter, empidParameter, statusParameter);
        }
    
        public virtual ObjectResult<Employeesalary_view_PageWise_ByMonth_Result> Employeesalary_view_PageWise_ByMonth(string month, Nullable<int> year, Nullable<int> empid, string status, Nullable<int> pageNumber, Nullable<int> rowsOfPage)
        {
            var monthParameter = month != null ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(string));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var empidParameter = empid.HasValue ?
                new ObjectParameter("Empid", empid) :
                new ObjectParameter("Empid", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("PageNumber", pageNumber) :
                new ObjectParameter("PageNumber", typeof(int));
    
            var rowsOfPageParameter = rowsOfPage.HasValue ?
                new ObjectParameter("RowsOfPage", rowsOfPage) :
                new ObjectParameter("RowsOfPage", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Employeesalary_view_PageWise_ByMonth_Result>("Employeesalary_view_PageWise_ByMonth", monthParameter, yearParameter, empidParameter, statusParameter, pageNumberParameter, rowsOfPageParameter);
        }
    
        public virtual ObjectResult<Employeesalary_viewAllByMonth_Result> Employeesalary_viewAllByMonth(string month, Nullable<int> year, Nullable<int> empid, string status)
        {
            var monthParameter = month != null ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(string));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var empidParameter = empid.HasValue ?
                new ObjectParameter("Empid", empid) :
                new ObjectParameter("Empid", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Employeesalary_viewAllByMonth_Result>("Employeesalary_viewAllByMonth", monthParameter, yearParameter, empidParameter, statusParameter);
        }
    
        public virtual ObjectResult<EmployeeSalary_ById_Result> EmployeeSalary_ById(Nullable<int> empid, string month, Nullable<int> year, Nullable<System.DateTime> fromdate, Nullable<System.DateTime> todate)
        {
            var empidParameter = empid.HasValue ?
                new ObjectParameter("empid", empid) :
                new ObjectParameter("empid", typeof(int));
    
            var monthParameter = month != null ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(string));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var fromdateParameter = fromdate.HasValue ?
                new ObjectParameter("fromdate", fromdate) :
                new ObjectParameter("fromdate", typeof(System.DateTime));
    
            var todateParameter = todate.HasValue ?
                new ObjectParameter("todate", todate) :
                new ObjectParameter("todate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EmployeeSalary_ById_Result>("EmployeeSalary_ById", empidParameter, monthParameter, yearParameter, fromdateParameter, todateParameter);
        }
    }
}
