//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MendinePayroll.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayConfig
    {
        public int PayConfigId { get; set; }
        public string PayConfigName { get; set; }
        public string PayConfigType { get; set; }
        public Nullable<bool> IScalculative { get; set; }
    }
}
