//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MendinePayroll.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryComponent
    {
        public int SalaryComponentID { get; set; }
        public string SalaryComponent1 { get; set; }
        public int SalaryComponentCode { get; set; }
        public Nullable<int> SalaryComponentTypeID { get; set; }
        public int PayGroupID { get; set; }
        public string Description { get; set; }
    }
}
