//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MendinePayroll.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tcomworklisthistory
    {
        public int activeworklistid { get; set; }
        public string wrkflwitemkey { get; set; }
        public string wrkflwitemactid { get; set; }
        public string currentstatus { get; set; }
        public string fromuserid { get; set; }
        public string touserid { get; set; }
        public Nullable<System.DateTime> startdatetime { get; set; }
        public string initiatedby { get; set; }
        public string activeflag { get; set; }
        public string approvaltag { get; set; }
        public string targetroleachieved { get; set; }
        public string cawactivityname { get; set; }
    }
}
