//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MendinePayroll.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tleaveapplicationhrd
    {
        public int applicationhdrid { get; set; }
        public string requestid { get; set; }
        public string applicationdate { get; set; }
        public string deleteflag { get; set; }
        public string approverempid { get; set; }
        public string approvaldate { get; set; }
        public string Applicationstatus { get; set; }
        public string createdby { get; set; }
        public string createdon { get; set; }
        public string updatedby { get; set; }
        public string updatedon { get; set; }
        public string approverremarks { get; set; }
    }
}
