//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MendinePayroll.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tleaveappdtl
    {
        public int applicationhdrid { get; set; }
        public Nullable<int> leaveid { get; set; }
        public string leavestartdate { get; set; }
        public string startdatehalfind { get; set; }
        public string leaveenddate { get; set; }
        public string enddayhalfind { get; set; }
        public Nullable<decimal> noofdays { get; set; }
        public string destinationcode { get; set; }
        public string contactaddress { get; set; }
        public string contactphoneno { get; set; }
        public string outstationpermissionind { get; set; }
        public string salaryadvancereqdind { get; set; }
        public Nullable<decimal> advanceamt { get; set; }
        public string leaveappliedfor { get; set; }
        public string ltctypecode { get; set; }
        public Nullable<decimal> blockyearid { get; set; }
        public string fitnesscertsubmitind { get; set; }
        public string leavereason { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public string updatedby { get; set; }
        public Nullable<System.DateTime> updatedon { get; set; }
        public string deleteflag { get; set; }
        public Nullable<System.DateTime> suffixfromdate { get; set; }
        public string suffixtodate { get; set; }
        public string leaveextendedind { get; set; }
        public string prefixfromdate { get; set; }
        public string prefixtodate { get; set; }
        public string noonindicator { get; set; }
        public string prefixindicator { get; set; }
        public string suffixindicator { get; set; }
        public string maternitytype { get; set; }
        public string childid { get; set; }
        public string Compoffrequestid { get; set; }
    }
}
